import type {
  DashboardBriefingData,
  DashboardKPI,
  DashboardModule,
  DashboardViewDefinition,
} from "./types";

const buildKpi = (kpi: DashboardKPI): DashboardKPI => kpi;

const operacaoModules: DashboardModule[] = [
  {
    id: "receita-mrr",
    title: "Receita & MRR",
    description: "Leitura mensal do motor de receita recorrente, expansão e previsibilidade de caixa futuro.",
    cadence: "Semanal para forecast, mensal para fechamento financeiro",
    sources: ["Planilha de Contratos", "Pipedrive", "Cálculo interno"],
    priorityPhase: 2,
    kpis: [
      buildKpi({
        id: "mrr-total",
        name: "MRR Total (R$)",
        currentValue: "R$ 148,2 mil",
        status: "green",
        formula: "Σ(valor do plano × clientes ativos no mês)",
        source: "Planilha de Contratos",
        frequency: "monthly",
        thresholds: { green: "Crescendo todo mês", yellow: "Crescimento < 8% por 2 meses", red: "Estagnado ou caindo" },
        executiveReading: "Mostra se a base recorrente está de fato expandindo.",
      }),
      buildKpi({
        id: "crescimento-mrr",
        name: "Crescimento MRR (%)",
        currentValue: "12,4%",
        status: "yellow",
        formula: "(MRR atual - MRR anterior) ÷ MRR anterior × 100",
        source: "Cálculo interno",
        frequency: "monthly",
        thresholds: { green: "> 15% ao mês", yellow: "8% a 15% ao mês", red: "< 8% por 2 meses" },
        executiveReading: "Sinaliza velocidade de crescimento, não apenas volume absoluto.",
      }),
      buildKpi({
        id: "new-mrr",
        name: "New MRR (R$)",
        currentValue: "R$ 22,6 mil",
        status: "green",
        formula: "Σ MRR de todos os contratos novos assinados no mês",
        source: "Pipedrive + Planilha de Contratos",
        frequency: "monthly",
        thresholds: { green: ">= meta mensal definida no setup", yellow: "50% a 99% da meta", red: "Zero new MRR no mês" },
        executiveReading: "Aponta a entrada de nova receita recorrente de OS e Advisory.",
      }),
      buildKpi({
        id: "churn-mrr",
        name: "Churn MRR (R$)",
        currentValue: "R$ 4,1 mil",
        status: "yellow",
        formula: "Σ MRR de clientes que cancelaram ou reduziram plano no mês",
        source: "Planilha de Contratos",
        frequency: "monthly",
        thresholds: { green: "< 5% do MRR total", yellow: "5% a 10%", red: "> 10%" },
        executiveReading: "Expõe perdas na base recorrente antes de virarem problema estrutural.",
      }),
      buildKpi({
        id: "forecast-mrr-3m",
        name: "Forecast MRR 3 meses (R$)",
        currentValue: "R$ 193 mil",
        status: "green",
        formula: "Pipeline ponderado + contratos já assinados e vigentes",
        source: "Pipedrive",
        frequency: "weekly",
        thresholds: { green: "Desvio <= 15% do realizado", yellow: "Desvio 15% a 30%", red: "Forecast < 70% da meta do próximo mês" },
        executiveReading: "Conecta a visão operacional ao que já deve cair de receita nos próximos meses.",
      }),
    ],
  },
  {
    id: "clientes-retencao",
    title: "Clientes & Retenção",
    description: "Saúde da carteira ativa, qualidade da entrega e sinais de risco de churn ou expansão.",
    cadence: "Semanal para exceções, mensal para score consolidado",
    sources: ["Planilha de Contratos", "Google Forms", "Checklist por cliente", "Pipedrive"],
    priorityPhase: 2,
    kpis: [
      buildKpi({
        id: "clientes-ativos",
        name: "Clientes Ativos (nº)",
        currentValue: "31",
        status: "green",
        formula: "Nº total de clientes com contrato recorrente ativo no último dia do mês",
        source: "Planilha de Contratos",
        frequency: "monthly",
        thresholds: { green: "Crescendo todo mês", yellow: "Estável sem crescimento por 2 meses", red: "Queda no total de clientes ativos" },
        executiveReading: "Base ativa que sustenta MRR e capacidade ocupada.",
      }),
      buildKpi({
        id: "churn-rate",
        name: "Churn Rate (%)",
        currentValue: "4,1%",
        status: "yellow",
        formula: "Clientes que cancelaram no mês ÷ total de clientes no início do mês × 100",
        source: "Planilha de Contratos",
        frequency: "monthly",
        thresholds: { green: "< 3%", yellow: "3% a 7%", red: "> 7% com RCA obrigatório" },
        executiveReading: "Indicador de vazamento da base e da qualidade percebida.",
      }),
      buildKpi({
        id: "nps-clientes",
        name: "NPS de Clientes GLX",
        currentValue: "8,3",
        status: "yellow",
        formula: "Média das notas de satisfação coletadas via formulário mensal",
        source: "Google Forms",
        frequency: "monthly",
        thresholds: { green: "> 8,5", yellow: "7,5 a 8,5", red: "< 7,5 com reunião imediata com detratores" },
        executiveReading: "Mostra percepção real do serviço e antecede churn silencioso.",
      }),
      buildKpi({
        id: "entregas-no-prazo",
        name: "Entregas no Prazo (%)",
        currentValue: "91%",
        status: "yellow",
        formula: "Entregas realizadas no prazo ÷ total de entregas previstas × 100",
        source: "Checklist por cliente",
        frequency: "weekly",
        thresholds: { green: "> 95%", yellow: "85% a 95%", red: "< 85%" },
        executiveReading: "Leitura operacional da disciplina de execução do time.",
      }),
      buildKpi({
        id: "tempo-onboarding",
        name: "Tempo Médio de Onboarding (dias)",
        currentValue: "17 dias",
        status: "yellow",
        formula: "Dias entre assinatura do contrato e cliente com dashboard operacional + 1ª reunião",
        source: "Planilha de Projetos",
        frequency: "monthly",
        thresholds: { green: "< 15 dias", yellow: "15 a 25 dias", red: "> 25 dias" },
        executiveReading: "Mostra eficiência da ativação inicial e do valor percebido cedo.",
      }),
      buildKpi({
        id: "health-score",
        name: "Health Score por Cliente (0-10)",
        currentValue: "7,6",
        status: "green",
        formula: "NPS 40% + entregas no prazo 30% + adimplência 20% + engajamento em reuniões 10%",
        source: "Cálculo interno (Forms + Checklist)",
        frequency: "monthly",
        thresholds: { green: "Todos os clientes > 7", yellow: "Qualquer cliente entre 5 e 7", red: "Qualquer cliente < 5" },
        executiveReading: "Prioriza quem precisa de plano de resgate antes de perder contrato.",
      }),
      buildKpi({
        id: "taxa-indicacao",
        name: "Taxa de Indicação (%)",
        currentValue: "24%",
        status: "yellow",
        formula: "Leads originados por indicação direta ÷ total de leads novos × 100",
        source: "Pipedrive (origem)",
        frequency: "monthly",
        thresholds: { green: "> 30%", yellow: "15% a 30%", red: "< 15%" },
        executiveReading: "Sinal de satisfação de carteira e qualidade da marca no mercado.",
      }),
    ],
  },
  {
    id: "financeiro-interno",
    title: "Financeiro Interno",
    description: "Saúde econômica, margem, CAC, inadimplência e produtividade da operação como negócio.",
    cadence: "Diário para caixa e inadimplência, mensal para rentabilidade",
    sources: ["ASAAS", "Planilha DRE", "Controle de Tempo", "Pipedrive"],
    priorityPhase: 2,
    kpis: [
      buildKpi({
        id: "receita-total-mensal",
        name: "Receita Total Mensal (R$)",
        currentValue: "R$ 176,9 mil",
        status: "green",
        formula: "MRR + receitas one-time faturadas no mês",
        source: "ASAAS + DRE",
        frequency: "monthly",
        thresholds: { green: ">= meta do mês", yellow: "80% a 99% da meta no dia 20", red: "< 80% da meta no dia 20" },
        executiveReading: "Consolida recorrência com projetos e setups do período.",
      }),
      buildKpi({
        id: "margem-liquida",
        name: "Margem Líquida (%)",
        currentValue: "32%",
        status: "yellow",
        formula: "(Receita total - custos operacionais) ÷ receita total × 100",
        source: "Planilha DRE",
        frequency: "monthly",
        thresholds: { green: "> 35%", yellow: "20% a 35%", red: "< 20%" },
        executiveReading: "Mostra se crescimento está virando caixa real para a empresa.",
      }),
      buildKpi({
        id: "cac",
        name: "CAC (R$)",
        currentValue: "R$ 8,4 mil",
        status: "green",
        formula: "Gasto total em marketing + vendas no mês ÷ novos clientes fechados",
        source: "DRE + Pipedrive",
        frequency: "monthly",
        thresholds: { green: "< 3x MRR médio do plano vendido", yellow: "3x a 6x MRR médio", red: "> 6x MRR médio" },
        executiveReading: "Garante que aquisição não destrua a economia unitária.",
      }),
      buildKpi({
        id: "fluxo-caixa-projetado",
        name: "Fluxo de Caixa Projetado (R$)",
        currentValue: "R$ 214 mil",
        status: "green",
        formula: "Saldo atual + recebimentos confirmados 60 dias - despesas previstas",
        source: "ASAAS + Planilha Financeira",
        frequency: "daily",
        thresholds: { green: "Positivo e crescente", yellow: "Positivo com < 1 mês de reserva", red: "Negativo em qualquer mês projetado" },
        executiveReading: "Protege liquidez e capacidade de manter operação e expansão.",
      }),
      buildKpi({
        id: "inadimplencia",
        name: "Inadimplência (%)",
        currentValue: "5,6%",
        status: "yellow",
        formula: "Faturas vencidas há mais de 15 dias ÷ receita total do mês × 100",
        source: "ASAAS",
        frequency: "weekly",
        thresholds: { green: "< 3%", yellow: "3% a 8%", red: "> 8%" },
        executiveReading: "Expõe risco de caixa e necessidade de acionamento de cobrança.",
      }),
      buildKpi({
        id: "receita-por-hora",
        name: "Receita por Hora (R$/h)",
        currentValue: "R$ 274/h",
        status: "yellow",
        formula: "Receita total do mês ÷ total de horas em entrega + reuniões + vendas + gestão",
        source: "DRE + Controle de Tempo",
        frequency: "monthly",
        thresholds: { green: "> R$ 300/h", yellow: "R$ 150 a R$ 300/h", red: "< R$ 150/h" },
        executiveReading: "Traduz eficiência operacional em retorno econômico.",
      }),
    ],
  },
  {
    id: "capacidade-operacao",
    title: "Capacidade & Operação",
    description: "Capacidade atual do time, pressão de atendimento e risco de gargalo na entrega.",
    cadence: "Semanal",
    sources: ["Planilha de Capacidade", "Controle de Tempo", "WhatsApp/Gmail"],
    priorityPhase: 3,
    kpis: [
      buildKpi({
        id: "utilizacao-capacidade",
        name: "Utilização de Capacidade (%)",
        currentValue: "84%",
        status: "green",
        formula: "Clientes ativos ÷ capacidade máxima do modelo × 100",
        source: "Planilha de Capacidade",
        frequency: "weekly",
        thresholds: { green: "70% a 85%", yellow: "85% a 95%", red: "> 95%" },
        executiveReading: "Mostra se ainda existe margem para vender sem estressar a entrega.",
      }),
      buildKpi({
        id: "horas-por-cliente-semana",
        name: "Horas por Cliente / Semana",
        currentValue: "4,7h",
        status: "yellow",
        formula: "Horas de entrega + reunião + gestão ÷ clientes ativos ÷ 4 semanas",
        source: "Controle de Tempo",
        frequency: "weekly",
        thresholds: { green: "< 4h", yellow: "4h a 6h", red: "> 6h" },
        executiveReading: "Se sobe demais, a operação está deixando de ser escalável.",
      }),
      buildKpi({
        id: "sla-resposta-clientes",
        name: "SLA Resposta Clientes (h)",
        currentValue: "3,1h",
        status: "yellow",
        formula: "Tempo médio entre mensagem do cliente e resposta da GLX em horário útil",
        source: "WhatsApp / Gmail",
        frequency: "daily",
        thresholds: { green: "< 2h", yellow: "2h a 6h", red: "> 8h" },
        executiveReading: "Liga diretamente experiência percebida à saúde de relacionamento.",
      }),
    ],
  },
];

const pipelineModules: DashboardModule[] = [
  {
    id: "topo-funil",
    title: "Topo do Funil",
    description: "Volume e qualidade do fluxo de entrada que abastece OS e Advisory.",
    cadence: "Semanal",
    sources: ["Pipedrive", "LinkedIn", "Google Calendar"],
    priorityPhase: 1,
    kpis: [
      buildKpi({
        id: "leads-totais",
        name: "Leads Totais Gerados",
        currentValue: "46",
        status: "green",
        formula: "Total de leads que entraram em contato ou foram prospectados no período",
        source: "Pipedrive / LinkedIn",
        frequency: "weekly",
        thresholds: { green: "> 40/mês", yellow: "20 a 40/mês", red: "< 20/mês por 2 meses" },
        executiveReading: "Base do funil e primeiro alerta de pipeline seco.",
      }),
      buildKpi({
        id: "leads-quentes",
        name: "Leads Quentes",
        currentValue: "17",
        status: "green",
        formula: "Leads com interesse claro movidos para qualificação",
        source: "Pipedrive",
        frequency: "weekly",
        thresholds: { green: "> 15/mês", yellow: "8 a 15/mês", red: "< 8/mês" },
        executiveReading: "Mede qualidade do targeting e da mensagem comercial.",
      }),
      buildKpi({
        id: "taxa-lead-quente",
        name: "Taxa Lead → Lead Quente (%)",
        currentValue: "37%",
        status: "green",
        formula: "Leads quentes ÷ leads totais × 100",
        source: "Cálculo interno — Pipedrive",
        frequency: "weekly",
        thresholds: { green: "> 35%", yellow: "20% a 35%", red: "< 20%" },
        executiveReading: "Indica se a abordagem está gerando interesse suficiente.",
      }),
      buildKpi({
        id: "calls-qualificacao",
        name: "Calls de Qualificação",
        currentValue: "12",
        status: "green",
        formula: "Nº de calls de qualificação realizadas no período",
        source: "Pipedrive / Google Calendar",
        frequency: "weekly",
        thresholds: { green: "> 10/mês", yellow: "5 a 10/mês", red: "< 5/mês" },
        executiveReading: "Transforma interesse em agenda efetiva de vendas.",
      }),
      buildKpi({
        id: "taxa-lead-call",
        name: "Taxa Lead Quente → Call (%)",
        currentValue: "71%",
        status: "green",
        formula: "Calls de qualificação realizadas ÷ leads quentes × 100",
        source: "Cálculo interno — Pipedrive",
        frequency: "weekly",
        thresholds: { green: "> 60%", yellow: "40% a 60%", red: "< 40%" },
        executiveReading: "Mede quantos leads quentes chegam à conversa estratégica.",
      }),
    ],
  },
  {
    id: "fechamento",
    title: "Fechamento",
    description: "Eficiência comercial da qualificação até a assinatura do contrato.",
    cadence: "Semanal para calls, mensal para conversão consolidada",
    sources: ["Pipedrive", "Google Calendar"],
    priorityPhase: 1,
    kpis: [
      buildKpi({
        id: "calls-fechamento",
        name: "Calls de Fechamento",
        currentValue: "7",
        status: "green",
        formula: "Nº de calls de fechamento com proposta apresentada",
        source: "Pipedrive / Google Calendar",
        frequency: "weekly",
        thresholds: { green: "> 6/mês", yellow: "3 a 6/mês", red: "< 3/mês" },
        executiveReading: "Sinal de pipeline comercial aquecido até a etapa de proposta.",
      }),
      buildKpi({
        id: "taxa-qualif-fechamento",
        name: "Taxa Qualif. → Fechamento (%)",
        currentValue: "58%",
        status: "yellow",
        formula: "Calls de fechamento ÷ calls de qualificação × 100",
        source: "Cálculo interno — Pipedrive",
        frequency: "monthly",
        thresholds: { green: "> 70%", yellow: "50% a 70%", red: "< 50%" },
        executiveReading: "Mostra se o lead está sendo aquecido de forma convincente.",
      }),
      buildKpi({
        id: "taxa-fechamento-contrato",
        name: "Taxa Fechamento → Contrato (%)",
        currentValue: "29%",
        status: "yellow",
        formula: "Contratos assinados ÷ calls de fechamento × 100",
        source: "Cálculo interno — Pipedrive",
        frequency: "monthly",
        thresholds: { green: "> 40%", yellow: "25% a 40%", red: "< 25%" },
        executiveReading: "Expõe fricção em proposta, preço ou percepção de valor.",
      }),
      buildKpi({
        id: "ciclo-lead-contrato",
        name: "Ciclo Médio Lead → Contrato (dias)",
        currentValue: "24 dias",
        status: "yellow",
        formula: "Média de dias entre o 1º contato e a assinatura do contrato",
        source: "Pipedrive",
        frequency: "monthly",
        thresholds: { green: "< 21 dias", yellow: "21 a 45 dias", red: "> 45 dias" },
        executiveReading: "Mostra travas no avanço comercial do lead até o fechamento.",
      }),
    ],
  },
  {
    id: "operation-system",
    title: "Operation System (OS) — Start / Pro",
    description: "Conversão do diagnóstico até setup e permanência no MRR de 12 meses.",
    cadence: "Semanal para diagnósticos, mensal para conversões do produto",
    sources: ["Google Calendar", "Pipedrive", "Planilha de Contratos"],
    priorityPhase: 1,
    kpis: [
      buildKpi({
        id: "diagnosticos-os",
        name: "Diagnósticos Agendados OS",
        currentValue: "5",
        status: "green",
        formula: "Reuniões de diagnóstico confirmadas com clientes OS no período",
        source: "Google Calendar / Pipedrive",
        frequency: "weekly",
        thresholds: { green: "> 4/mês", yellow: "2 a 4/mês", red: "< 2/mês" },
        executiveReading: "Indica tração no produto OS após calls de fechamento.",
      }),
      buildKpi({
        id: "setups-fechados-os",
        name: "Setups Fechados OS",
        currentValue: "3",
        status: "green",
        formula: "Contratos de Setup assinados após diagnóstico",
        source: "Planilha de Contratos — Pipedrive",
        frequency: "monthly",
        thresholds: { green: "> 3/mês", yellow: "1 a 3/mês", red: "0 setups no mês" },
        executiveReading: "Mostra capacidade comercial de converter diagnóstico em projeto.",
      }),
      buildKpi({
        id: "taxa-diagnostico-setup",
        name: "Taxa Diagnóstico → Setup (%)",
        currentValue: "68%",
        status: "yellow",
        formula: "Setups fechados ÷ diagnósticos realizados × 100",
        source: "Cálculo interno — Pipedrive",
        frequency: "monthly",
        thresholds: { green: "> 70%", yellow: "50% a 70%", red: "< 50%" },
        executiveReading: "Valida se o diagnóstico gera urgência e percepção clara de valor.",
      }),
      buildKpi({
        id: "taxa-setup-mrr",
        name: "Taxa Setup → MRR 12m (%)",
        currentValue: "74%",
        status: "yellow",
        formula: "MRR 12m assinados ÷ setups concluídos × 100",
        source: "Cálculo interno — Contratos",
        frequency: "monthly",
        thresholds: { green: "> 80%", yellow: "60% a 80%", red: "< 60%" },
        executiveReading: "KPI crítico do produto OS: setup precisa virar recorrência.",
      }),
      buildKpi({
        id: "os-start-mrr12",
        name: "OS Start Ativos % MRR 12m",
        currentValue: "78%",
        status: "yellow",
        formula: "Clientes OS Start em MRR 12m ÷ total de clientes OS Start ativos × 100",
        source: "Planilha de Contratos",
        frequency: "monthly",
        thresholds: { green: "> 80%", yellow: "60% a 80%", red: "< 60%" },
        executiveReading: "Mostra se o Start está conseguindo provar valor e reter.",
      }),
      buildKpi({
        id: "os-pro-mrr12",
        name: "OS Pro Ativos % MRR 12m",
        currentValue: "82%",
        status: "green",
        formula: "Clientes OS Pro em MRR 12m ÷ total de clientes OS Pro ativos × 100",
        source: "Planilha de Contratos",
        frequency: "monthly",
        thresholds: { green: "> 80%", yellow: "60% a 80%", red: "< 60%" },
        executiveReading: "Indica a robustez do plano Pro em virar receita recorrente longa.",
      }),
    ],
  },
  {
    id: "advisory",
    title: "Advisory — Board / Scale",
    description: "Sinais de fechamento e renovação do produto sem setup, focado em recorrência consultiva.",
    cadence: "Mensal",
    sources: ["Pipedrive", "Planilha de Contratos"],
    priorityPhase: 1,
    kpis: [
      buildKpi({
        id: "advisory-fechados",
        name: "Advisory Fechados",
        currentValue: "1",
        status: "yellow",
        formula: "Contratos Advisory fechados no período",
        source: "Pipedrive",
        frequency: "monthly",
        thresholds: { green: "> 2/mês", yellow: "1/mês", red: "0 no mês" },
        executiveReading: "Controla o ritmo do produto consultivo que entra direto em MRR.",
      }),
      buildKpi({
        id: "advisory-ativos",
        name: "Advisory Ativos Total (n)",
        currentValue: "8",
        status: "green",
        formula: "Total de clientes Advisory ativos",
        source: "Planilha de Contratos",
        frequency: "monthly",
        thresholds: { green: "Crescendo todo mês", yellow: "Estável por 2 meses", red: "Queda na base" },
        executiveReading: "Base consultiva ativa com impacto direto na previsibilidade.",
      }),
      buildKpi({
        id: "renovacao-advisory",
        name: "Taxa Renovação Advisory 6m (%)",
        currentValue: "67%",
        status: "yellow",
        formula: "Renovações Advisory ÷ contratos elegíveis à renovação × 100",
        source: "Planilha de Contratos",
        frequency: "monthly",
        thresholds: { green: "> 75%", yellow: "50% a 75%", red: "< 50%" },
        executiveReading: "Mostra retenção do advisory e valor percebido após 6 meses.",
      }),
    ],
  },
  {
    id: "consolidada",
    title: "Visão Consolidada",
    description: "Camada executiva que combina valor ponderado, ticket médio e carga de setups em andamento.",
    cadence: "Semanal",
    sources: ["Pipedrive", "Planilha de Contratos"],
    priorityPhase: 1,
    kpis: [
      buildKpi({
        id: "pipeline-ponderado",
        name: "Pipeline Ponderado Total (R$)",
        currentValue: "R$ 462 mil",
        status: "green",
        formula: "Σ valor do contrato × probabilidade por etapa",
        source: "Pipedrive",
        frequency: "weekly",
        thresholds: { green: "> 3x a meta mensal", yellow: "2x a 3x a meta", red: "< 2x a meta mensal" },
        executiveReading: "Principal leitura de garantia de crescimento futuro.",
      }),
      buildKpi({
        id: "acv-medio",
        name: "ACV Valor Médio Contrato (R$)",
        currentValue: "R$ 21,8 mil",
        status: "green",
        formula: "Receita dos novos contratos assinados ÷ nº de novos contratos",
        source: "Pipedrive",
        frequency: "monthly",
        thresholds: { green: "Estável ou crescente", yellow: "Queda < 15% vs mês anterior", red: "Queda > 15% por 2 meses" },
        executiveReading: "Monitora qualidade do mix comercial e do ticket vendido.",
      }),
      buildKpi({
        id: "setups-andamento",
        name: "Setups em Andamento (n)",
        currentValue: "4",
        status: "green",
        formula: "Clientes atualmente no ciclo de setup de 60 dias",
        source: "Planilha de Contratos",
        frequency: "weekly",
        thresholds: { green: "> 2 em andamento", yellow: "1 em andamento", red: "0 por 2 meses" },
        executiveReading: "Ponte entre vendas fechadas e futura conversão em MRR de 12 meses.",
      }),
    ],
  },
];

const views: DashboardViewDefinition[] = [
  {
    id: "pipeline",
    title: "Visão 2 — Pipeline & Funil",
    executiveQuestion: "O crescimento dos próximos 30 a 60 dias está garantido?",
    cadence: "Revisão semanal de 30 minutos, com leitura diária quando necessário.",
    description: "Painel do para-brisa comercial da GLX: mostra entrada de leads, calls, fechamento e a garantia de receita futura para OS e Advisory.",
    heroTitle: "O crescimento futuro está garantido?",
    heroCopy: "Esta visão consolida 21 KPIs em 5 blocos para leitura semanal do CEO e dos sócios, com foco em leads, calls, contratos, setups e MRR futuro.",
    heroKpis: [
      { label: "Pipeline ponderado", value: "R$ 462 mil", status: "green" },
      { label: "Leads quentes", value: "17", status: "green" },
      { label: "Taxa fechamento → contrato", value: "29%", status: "yellow" },
      { label: "Setups em andamento", value: "4", status: "green" },
    ],
    modules: pipelineModules,
  },
  {
    id: "operacao",
    title: "Visão 1 — Operação Interna",
    executiveQuestion: "A empresa está saudável agora e protegendo o dinheiro que ganhou?",
    cadence: "Revisão semanal nos críticos e fechamento mensal no scorecard completo.",
    description: "Painel do retrovisor e da execução atual: receita, retenção, financeiro e capacidade de entrega com leitura executiva e score de saúde.",
    heroTitle: "Operação interna com 21 KPIs em 4 módulos para proteger margem, retenção e capacidade.",
    heroCopy: "Esta visão usa ASAAS, Google Forms, Planilha de Contratos, DRE e Controle de Tempo, seguindo exatamente as fontes descritas no briefing.",
    heroKpis: [
      { label: "MRR total", value: "R$ 148,2 mil", status: "green" },
      { label: "Churn rate", value: "4,1%", status: "yellow" },
      { label: "Margem líquida", value: "32%", status: "yellow" },
      { label: "Capacidade usada", value: "84%", status: "green" },
    ],
    modules: operacaoModules,
  },
];

export const ADMIN_DASHBOARD_MOCK_DATA: DashboardBriefingData = {
  views,
  integrations: [
    {
      id: "pipedrive",
      source: "Pipedrive CRM",
      provides: ["Leads", "Leads quentes", "Calls", "Propostas", "Contratos", "Pipeline ponderado", "ACV", "Origem do lead"],
      integrationMethod: "API REST nativa + webhook em mudança de etapa do funil",
      cadence: "Tempo real",
      scope: ["pipeline", "operacao"],
    },
    {
      id: "asaas",
      source: "ASAAS",
      provides: ["Receita mensal", "Inadimplência", "Fluxo de caixa projetado", "Recebimentos previstos"],
      integrationMethod: "REST API com pull diário automatizado via Make",
      cadence: "Diária",
      scope: ["operacao"],
    },
    {
      id: "google-calendar",
      source: "Google Calendar",
      provides: ["Calls de qualificação", "Calls de fechamento", "Diagnósticos OS", "Reuniões com clientes"],
      integrationMethod: "Google Calendar API com contagem por labels como CALL-QUAL, CALL-FECH e DIAG-OS",
      cadence: "Diária",
      scope: ["pipeline"],
    },
    {
      id: "google-forms",
      source: "Google Forms / Sheets",
      provides: ["NPS de clientes", "Engajamento nas reuniões"],
      integrationMethod: "Google Forms conectado ao Sheets com pull semanal via Make",
      cadence: "Semanal",
      scope: ["operacao"],
    },
    {
      id: "contratos",
      source: "Planilha de Contratos",
      provides: ["Clientes ativos", "MRR por cliente", "Churn", "Tipo de plano", "Setups em andamento", "Status MRR 12m", "Status Advisory"],
      integrationMethod: "Google Sheets API com atualização manual semanal pelo CEO e leitura automática",
      cadence: "Semanal",
      scope: ["pipeline", "operacao"],
    },
    {
      id: "dre",
      source: "Planilha DRE",
      provides: ["Margem líquida", "Receita total", "CAC", "Receita por hora"],
      integrationMethod: "Google Sheets API com atualização manual mensal",
      cadence: "Mensal",
      scope: ["operacao"],
    },
    {
      id: "tempo",
      source: "Controle de Tempo",
      provides: ["Horas por cliente", "Horas totais de operação", "Receita por hora"],
      integrationMethod: "Exportação manual mensal ou integração futura via Notion API",
      cadence: "Mensal",
      scope: ["operacao"],
    },
  ],
  alertRules: [
    {
      level: "green",
      title: "Verde",
      description: "KPI em meta ou acima da meta.",
      expectedAction: "Sem ação corretiva. Registrar o que está funcionando para replicar.",
    },
    {
      level: "yellow",
      title: "Amarelo",
      description: "KPI entre faixa de atenção e meta, ou tendência negativa identificada.",
      expectedAction: "Investigar causa raiz em até 7 dias, levar para a próxima reunião semanal e monitorar por 2 ciclos.",
    },
    {
      level: "red",
      title: "Vermelho",
      description: "KPI abaixo do limiar crítico ou em tendência negativa por 2+ semanas.",
      expectedAction: "Ação em 24h, RCA obrigatório, dono definido e prazo documentado.",
    },
  ],
  roadmap: [
    {
      phase: 1,
      title: "Pipeline & Funil",
      timeline: "Semana 1-2",
      scope: "Visão 2 completa com blocos 1-5, integrações Pipedrive + Google Calendar + Planilha de Contratos.",
      justification: "O briefing prioriza pipeline primeiro para garantir crescimento futuro antes de otimizar operação.",
    },
    {
      phase: 2,
      title: "Operação — Receita, Clientes e Financeiro",
      timeline: "Semana 3-4",
      scope: "Visão 1 módulos 1-3 com ASAAS, Google Forms, Contratos e DRE.",
      justification: "Depois de garantir topo e meio do funil, a operação precisa proteger MRR, margem e retenção.",
    },
    {
      phase: 3,
      title: "Capacidade & Scorecard Executivo",
      timeline: "Semana 5",
      scope: "Módulo 4 de operação e scorecard consolidado com os 21 KPIs operacionais.",
      justification: "Capacidade só faz sentido depois que receita, retenção e financeiro estiverem estabilizados.",
    },
    {
      phase: 4,
      title: "Alertas automáticos e polish visual",
      timeline: "Semana 6",
      scope: "Semáforos ativos, push de alertas vermelhos, estados de loading/error e refinamento final de UX.",
      justification: "Automação e acabamento vêm por último para consolidar o uso executivo recorrente.",
    },
  ],
  assumptions: [
    "As probabilidades do pipeline ponderado seguem o briefing: Lead Quente 10%, Call Qualificação 30%, Call Fechamento 60%, Proposta enviada 80%.",
    "Os conectores externos estão preparados como estrutura de integração futura; nesta etapa o dashboard usa dados mockados consistentes com o briefing.",
    "A página 9 do PDF veio sem conteúdo textual extraível, mas os 21 KPIs da Visão 2 foram recompostos integralmente pela contagem e continuidade entre as páginas 8, 10 e 11.",
  ],
};
